version: 2
updates:
  # Main
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo

  # npm
  - package-ecosystem: npm
    directory: "/npm"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # Docker
  - package-ecosystem: docker
    directory: "/base"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/dotnet"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/go"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/haskell"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/java"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/npm"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: node
        versions:
          # NOTE: Node 12 is the current LTS version. See https://github.com/nodejs/Release#readme
          - ">= 13.a, < 15"
  - package-ecosystem: docker
    directory: "/php"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/python"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/swift"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
