language: ruby

services:
  - docker

env:
  - BUILD_CONTEXT=base
  - BUILD_CONTEXT=go
  - BUILD_CONTEXT=java
  - BUILD_CONTEXT=npm
  - BUILD_CONTEXT=php
  - BUILD_CONTEXT=python
  - BUILD_CONTEXT=ruby
  - BUILD_CONTEXT=swift

before_install:
  - gem install bundler

script:
  - set -e
  - export TAG="${TRAVIS_TAG:-${TRAVIS_COMMIT}}"
  - docker info
  - bundle exec rake dockerfile:generate
  - bundle exec rake dockerfile:verify
  - bundle exec rake docker:build
  - bundle exec rake docker:run
  - bundle exec rake docker:test

branches:
  only:
    - master
    - /^\d+\.\d+.\d+$/ # for tags; e.g. `3.2.1`, `0.3.1`

deploy:
  provider: script
  skip_cleanup: true
  script: rvm . do bundle exec rake docker:push
  on:
    tags: true
