FROM debian:buster-20190910

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

# Install Java
ENV JAVA_VERSION 12.0.1
ENV PATH /usr/local/java/bin:$PATH
ARG TAR_URL=https://download.java.net/java/GA/jdk${JAVA_VERSION}/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-${JAVA_VERSION}_linux-x64_bin.tar.gz
ARG SHA256_URL=https://download.java.net/java/GA/jdk${JAVA_VERSION}/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-${JAVA_VERSION}_linux-x64_bin.tar.gz.sha256
RUN curl -fsSLO --compressed $TAR_URL && \
    curl -fsSL -o sha256.txt --compressed $SHA256_URL && \
    echo "$(cat sha256.txt) *openjdk-${JAVA_VERSION}_linux-x64_bin.tar.gz" | sha256sum --check --strict && \
    mkdir -p /usr/local/java && \
    tar -xzf "openjdk-${JAVA_VERSION}_linux-x64_bin.tar.gz" -C /usr/local/java --strip-components=1 && \
    rm -rf "openjdk-${JAVA_VERSION}_linux-x64_bin.tar.gz" sha256.txt

# Install Maven
ENV MAVEN_VERSION 3.6.2
ENV PATH /usr/local/maven/bin:$PATH
ARG MAVEN_BINARY_URL=https://www.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
RUN curl -fsSL --compressed "${MAVEN_BINARY_URL}" -o maven-bin.tar.gz && \
    curl -fsSL --compressed "${MAVEN_BINARY_URL}.sha512" | xargs -I {} echo "{} *maven-bin.tar.gz" | sha512sum --check --strict && \
    mkdir -p /usr/local/maven && \
    tar -xzf maven-bin.tar.gz -C /usr/local/maven --strip-components 1 && \
    rm maven-bin.tar.gz

# Following instructions should be run by $RUNNER_USER
USER $RUNNER_USER

<%= ERB.new(File.read('base/Dockerfile.build-ruby.erb')).result %>

CMD java -version && javac -version && mvn -v
