FROM python:3.7.4-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

RUN pip install --upgrade pip && pip install pipenv

<%= ERB.new(File.read('base/Dockerfile.build-ruby.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD python --version && pip --version
