FROM debian:buster-20191118

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.build-ruby.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ruby -v && gem -v && bundle -v
