name: Test

on:
  push:
    branches:
      - master
    tags:
      # e.g. `3.2.1`, `0.3.1`
      - "[0-9]*.[0-9]*.[0-9]*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-context:
          - base
          - go
          - haskell
          - java
          - npm
          - php
          - python
          - ruby
          - swift
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Setup gems
        run: |
          gem install bundler --no-document
          bundle install --jobs=4 --retry=3 --path=vendor/bundle
      - name: Build and test the Docker image
        run: |
          export TAG="$(echo ${GITHUB_REF} | sed 's!refs/tags/!!' | sed 's!/!_!g')"
          docker info
          bundle exec rake dockerfile:generate
          bundle exec rake dockerfile:verify
          bundle exec rake docker:build
          bundle exec rake docker:run
        env:
          BUILD_CONTEXT: ${{ matrix.build-context }}
      - name: Publish the Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export TAG="$(echo ${GITHUB_REF} | sed 's!refs/tags/!!' | sed 's!/!_!g')"
          bundle exec rake docker:push
        env:
          BUILD_CONTEXT: ${{ matrix.build-context }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
