FROM node:12.13.0-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

RUN npm install --global "npm@${DEVON_REX_NPM_VERSION}"

# Following instructions should be run by $RUNNER_USER
USER $RUNNER_USER

<%= ERB.new(File.read('base/Dockerfile.build-ruby.erb')).result %>

CMD node -v && npm -v && yarn -v
